
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    instance-id: ${spring.application.name}:${random.value}
