management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: '1.0'
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    instance-id: ${spring.application.name}:${random.value}
resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        permittedNumberOfCallsInHalfOpenState: '3'
        failureRateThreshold: '50'
        slidingWindowSize: '50'
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: '20'
        waitDurationInOpenState: 50s

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/01_employee_db

springdoc:
  api-docs:
    path: /api-docs
app:
  fallback:
    method: defaultGetEmployeeById
  emp:
    service: EMPLOYEE-SERVICE
server:
  port: '8081'
logging:
  file:
    name: F:/LogFiles/employee-service.log